/**
 * Created by Jayakumar Mogenahall on 25/04/2023.
 */

public with sharing class DimensionWrapper {
    public String DimType;
    public Decimal Weight;
    public Decimal Depth;
    public Decimal Height;
    public Decimal Volume;
    public Decimal TotalCartoonInPallet;
    public Decimal TotalUnitsInCartoon;
    public Decimal TotalUnitsInPallet;
    public String MaterialCode;
    public String Id;
}